const TR_STATUS = {
  CREATED: "CREATED",
  AWAITING_PAYMENT: "AWAITING_PAYMENT",
  PARTIALLY_FUNDED: "PARTIALLY_FUNDED",
  FUNDED: "FUNDED",
  // VENDOR_ACKNOWLEDGES: "VENDOR_ACKNOWLEDGES",
  AWAITING_RELEASE: "AWAITING_RELEASE",
  RELEASED: "RELEASED",
  REFUNDED: "REFUNDED",
  DISPUTED: "DISPUTED",
  EXPIRED: "EXPIRED",
} as const;

export type EscrowStatus = keyof typeof TR_STATUS;

export default TR_STATUS;
